// Planificación 2026-2027; las notas personales permanecen en IndexedDB.
window.DIDACTICA_UPDATE = {
  "revision": "didactica-2026-2027-v10.1",
  "students4H": [
    "Almánzar Martínez, Rihanny NV",
    "Dorgil, Franchesca NV",
    "Gerez Espinosa, Noel",
    "Hernández Vásquez, Saul De Jesús",
    "Morel Muñoz, Jeyco",
    "Santos Ramos, Rosalba Esthefany NV",
    "Tavarez, Chelsea Winifer"
  ],
  "activities": [
    {
      "id": "seed-MF_632_3-ACT-01",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-08-31",
      "code": "ACT-01",
      "number": 1,
      "title": "Presentación del reto y elaboración del briefing del proyecto multimedia.",
      "points": 3,
      "type": "Actividad",
      "raCode": "RA6.1",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-02",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-09-07",
      "code": "ACT-02",
      "number": 2,
      "title": "Investigación de usuarios y análisis de referentes (Benchmarking).",
      "points": 3,
      "type": "Actividad",
      "raCode": "RA6.1",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-03",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-09-14",
      "code": "ACT-03",
      "number": 3,
      "title": "Arquitectura de información: mapa de navegación y estructura de contenidos.",
      "points": 3,
      "type": "Actividad",
      "raCode": "RA6.1",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-04",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-09-21",
      "code": "ACT-04",
      "number": 4,
      "title": "Elaboración de wireframes de baja fidelidad.",
      "points": 3,
      "type": "Actividad",
      "raCode": "RA6.1",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-05",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-09-28",
      "code": "ACT-05",
      "number": 5,
      "title": "Desarrollo del sistema visual e identidad gráfica del proyecto.",
      "points": 3,
      "type": "Actividad",
      "raCode": "RA6.1",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-06",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-10-05",
      "code": "ACT-06",
      "number": 6,
      "title": "Construcción del prototipo de alta fidelidad en Figma.",
      "points": 3,
      "type": "Actividad",
      "raCode": "RA6.1",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-07",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-10-12",
      "code": "ACT-07",
      "number": 7,
      "title": "Configuración de navegación e interacciones del prototipo.",
      "points": 3,
      "type": "Actividad",
      "raCode": "RA6.1",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-08",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-10-20",
      "code": "ACT-08",
      "number": 8,
      "title": "Aplicación de pruebas de usabilidad y análisis de resultados.",
      "points": 3,
      "type": "Actividad",
      "raCode": "RA6.1",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-09",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-10-26",
      "code": "ACT-09",
      "number": 9,
      "title": "Ajuste, presentación y defensa del prototipo interactivo.",
      "points": 3,
      "type": "Actividad",
      "raCode": "RA6.1",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-10",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-11-02",
      "code": "ACT-10",
      "number": 10,
      "title": "Elaboración del portafolio digital y reflexión sobre el proyecto.",
      "points": 3,
      "type": "Actividad",
      "raCode": "RA6.1",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-11",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-11-10",
      "code": "ACT-11",
      "number": 11,
      "title": "Análisis de interfaces digitales y patrones UI.",
      "points": 4,
      "type": "Actividad",
      "raCode": "RA6.2",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-12",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-11-16",
      "code": "ACT-12",
      "number": 12,
      "title": "Diseño de pantallas y componentes gráficos del proyecto.",
      "points": 4,
      "type": "Actividad",
      "raCode": "RA6.2",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-13",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-11-24",
      "code": "ACT-13",
      "number": 13,
      "title": "Diseño del recorrido del usuario (User Flow).",
      "points": 4,
      "type": "Actividad",
      "raCode": "RA6.2",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-14",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-11-30",
      "code": "ACT-14",
      "number": 14,
      "title": "Desarrollo de un prototipo funcional con enlaces, estados y transiciones.",
      "points": 4,
      "type": "Actividad",
      "raCode": "RA6.2",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-15",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-12-09",
      "code": "ACT-15",
      "number": 15,
      "title": "Integración de recursos multimedia: imágenes, audio, video y animaciones.",
      "points": 4,
      "type": "Actividad",
      "raCode": "RA6.2",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-16",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2026-12-14",
      "code": "ACT-16",
      "number": 16,
      "title": "Creación de botones, componentes interactivos y microinteracciones.",
      "points": 4,
      "type": "Actividad",
      "raCode": "RA6.2",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-17",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-01-11",
      "code": "ACT-17",
      "number": 17,
      "title": "Evaluación de accesibilidad del producto digital mediante criterios WCAG.",
      "points": 4,
      "type": "Actividad",
      "raCode": "RA6.2",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-18",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-01-19",
      "code": "ACT-18",
      "number": 18,
      "title": "Adaptación del proyecto incorporando mejoras de accesibilidad.",
      "points": 4,
      "type": "Actividad",
      "raCode": "RA6.2",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-19",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-01-27",
      "code": "ACT-19",
      "number": 19,
      "title": "Preparación y optimización del producto interactivo para publicación digital.",
      "points": 4,
      "type": "Actividad",
      "raCode": "RA6.2",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-20",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-02-02",
      "code": "ACT-20",
      "number": 20,
      "title": "Publicación web y comprobación del funcionamiento en diferentes dispositivos.",
      "points": 4,
      "type": "Actividad",
      "raCode": "RA6.2",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-21",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-02-08",
      "code": "ACT-21",
      "number": 21,
      "title": "Análisis de criterios de calidad del producto multimedia.",
      "points": 2,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-22",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-02-15",
      "code": "ACT-22",
      "number": 22,
      "title": "Revisión de especificaciones mediante lista de verificación.",
      "points": 2,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-23",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-02-22",
      "code": "ACT-23",
      "number": 23,
      "title": "Pruebas de compatibilidad en diferentes dispositivos.",
      "points": 2,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-24",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-03-01",
      "code": "ACT-24",
      "number": 24,
      "title": "Optimización de imágenes, audio, video y recursos multimedia.",
      "points": 2,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-25",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-03-09",
      "code": "ACT-25",
      "number": 25,
      "title": "Evaluación funcional de navegación, botones, formularios y controles.",
      "points": 2,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-26",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-03-15",
      "code": "ACT-26",
      "number": 26,
      "title": "Verificación de accesibilidad digital según criterios WCAG.",
      "points": 2,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-27",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-03-30",
      "code": "ACT-27",
      "number": 27,
      "title": "Elaboración del informe técnico de calidad del proyecto.",
      "points": 2,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-28",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-04-02",
      "code": "ACT-28",
      "number": 28,
      "title": "Creación del manual de usuario del producto multimedia.",
      "points": 2,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-29",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-04-07",
      "code": "ACT-29",
      "number": 29,
      "title": "Adaptación del producto multimedia para diferentes plataformas y soportes.",
      "points": 2,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-30",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-04-17",
      "code": "ACT-30",
      "number": 30,
      "title": "Planificación de la estrategia de publicación y distribución digital.",
      "points": 2,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": "Fecha original conservada; revisar calendario."
    },
    {
      "id": "seed-MF_632_3-ACT-31",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-04-26",
      "code": "ACT-31",
      "number": 31,
      "title": "Integración de tecnologías emergentes: IA, RA, WebAR o códigos QR.",
      "points": 3,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-32",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-05-08",
      "code": "ACT-32",
      "number": 32,
      "title": "Elaboración del plan de mantenimiento y mejora continua del proyecto.",
      "points": 3,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": "Fecha original conservada; revisar calendario."
    },
    {
      "id": "seed-MF_632_3-ACT-33",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-05-14",
      "code": "ACT-33",
      "number": 33,
      "title": "Reflexión sobre impacto digital, accesibilidad, privacidad y ética.",
      "points": 2,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": ""
    },
    {
      "id": "seed-MF_632_3-ACT-34",
      "moduleCode": "MF_632_3",
      "materiaId": null,
      "date": "2027-05-23",
      "code": "ACT-34",
      "number": 34,
      "title": "Presentación y defensa de la memoria final del proyecto multimedia.",
      "points": 2,
      "type": "Actividad",
      "raCode": "RA6.3",
      "source": "Cursos_didactica_2026-2027_actualizado.xlsx / Datos para act 6",
      "seeded": true,
      "dateNote": "Fecha original conservada; revisar calendario."
    },
    {
      "id": "seed-ARTES-4H-ACT-01",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-08-24",
      "code": "ACT-01",
      "number": 1,
      "title": "Diagnóstico inicial y autorretrato simbólico de identidad.",
      "points": null,
      "type": "Diagnóstico",
      "raCode": "",
      "period": "P1",
      "project": 1,
      "gradingKind": "diagnostic",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-02",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-08-31",
      "code": "ACT-02",
      "number": 2,
      "title": "Organización del dossier y definición de metas personales.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P1",
      "project": 1,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-03",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-09-07",
      "code": "ACT-03",
      "number": 3,
      "title": "Autobiografía breve y análisis FODA personal.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P1",
      "project": 1,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-04",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-09-14",
      "code": "ACT-04",
      "number": 4,
      "title": "Plan de progreso y compromiso ético del estudiante de Artes.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P1",
      "project": 1,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-05",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-09-21",
      "code": "ACT-05",
      "number": 5,
      "title": "Galería y presentación del dossier de identidad.",
      "points": 40,
      "type": "Proyecto",
      "raCode": "",
      "period": "P1",
      "project": 1,
      "gradingKind": "final",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-06",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-09-28",
      "code": "ACT-06",
      "number": 6,
      "title": "Análisis de autorretratos y mensajes audiovisuales.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P1",
      "project": 2,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-07",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-10-05",
      "code": "ACT-07",
      "number": 7,
      "title": "Guion, storyboard y plan de producción audiovisual.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P1",
      "project": 2,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-08",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-10-12",
      "code": "ACT-08",
      "number": 8,
      "title": "Captura de imagen, voz y sonido del autorretrato.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P1",
      "project": 2,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-09",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-10-19",
      "code": "ACT-09",
      "number": 9,
      "title": "Edición, títulos, créditos y revisión entre pares.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P1",
      "project": 2,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-10",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-10-26",
      "code": "ACT-10",
      "number": 10,
      "title": "Muestra final del autorretrato audiovisual.",
      "points": 40,
      "type": "Proyecto",
      "raCode": "",
      "period": "P1",
      "project": 2,
      "gradingKind": "final",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-11",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-11-02",
      "code": "ACT-11",
      "number": 11,
      "title": "Análisis de arte, cultura y representación en los medios.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P2",
      "project": 3,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-12",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-11-16",
      "code": "ACT-12",
      "number": 12,
      "title": "Selección del caso; construcción de tesis y argumentos.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P2",
      "project": 3,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-13",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-11-23",
      "code": "ACT-13",
      "number": 13,
      "title": "Producción de infografía, fotocómic o pódcast; preparación del panel.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P2",
      "project": 3,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-14",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-11-30",
      "code": "ACT-14",
      "number": 14,
      "title": "Panel argumentativo y presentación de la pieza cultural.",
      "points": 40,
      "type": "Proyecto",
      "raCode": "",
      "period": "P2",
      "project": 3,
      "gradingKind": "final",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-15",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-12-07",
      "code": "ACT-15",
      "number": 15,
      "title": "Investigación de una práctica o memoria cultural comunitaria.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P2",
      "project": 4,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-16",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2026-12-14",
      "code": "ACT-16",
      "number": 16,
      "title": "Diseño de secuencia visual, entrevistas, permisos y producción.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P2",
      "project": 4,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-17",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-01-11",
      "code": "ACT-17",
      "number": 17,
      "title": "Selección y edición de material; texto curatorial y créditos.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P2",
      "project": 4,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-18",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-01-18",
      "code": "ACT-18",
      "number": 18,
      "title": "Muestra y reflexión ética sobre la representación cultural.",
      "points": 40,
      "type": "Proyecto",
      "raCode": "",
      "period": "P2",
      "project": 4,
      "gradingKind": "final",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-19",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-02-01",
      "code": "ACT-19",
      "number": 19,
      "title": "Estudio de casos y rasgos del emprendedor cultural.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P3",
      "project": 5,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-20",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-02-08",
      "code": "ACT-20",
      "number": 20,
      "title": "Selección de iniciativa; entrevista y lienzo de oportunidad.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P3",
      "project": 5,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-21",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-02-15",
      "code": "ACT-21",
      "number": 21,
      "title": "Investigación o entrevista; elaboración del perfil multimedia.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P3",
      "project": 5,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-22",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-02-22",
      "code": "ACT-22",
      "number": 22,
      "title": "Feria de perfiles y pitch de oportunidad cultural.",
      "points": 40,
      "type": "Proyecto",
      "raCode": "",
      "period": "P3",
      "project": 5,
      "gradingKind": "final",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-23",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-03-01",
      "code": "ACT-23",
      "number": 23,
      "title": "Inventario de sectores, actores y fuentes culturales.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P3",
      "project": 6,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-24",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-03-08",
      "code": "ACT-24",
      "number": 24,
      "title": "Diseño del mapa, campos de datos e iconografía.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P3",
      "project": 6,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-25",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-03-15",
      "code": "ACT-25",
      "number": 25,
      "title": "Recopilación, depuración y análisis de oportunidades locales.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P3",
      "project": 6,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-26",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-03-29",
      "code": "ACT-26",
      "number": 26,
      "title": "Presentación del mapa y defensa de una oportunidad local.",
      "points": 40,
      "type": "Proyecto",
      "raCode": "",
      "period": "P3",
      "project": 6,
      "gradingKind": "final",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-27",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-04-05",
      "code": "ACT-27",
      "number": 27,
      "title": "Selección y justificación de una necesidad cultural real.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P4",
      "project": 7,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-28",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-04-12",
      "code": "ACT-28",
      "number": 28,
      "title": "Definición de público, objetivos, producto y FODA.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P4",
      "project": 7,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-29",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-04-19",
      "code": "ACT-29",
      "number": 29,
      "title": "Cronograma, roles, recursos, riesgos y borrador del proyecto.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P4",
      "project": 7,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-30",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-04-26",
      "code": "ACT-30",
      "number": 30,
      "title": "Clínica de presentación y revisión del proyecto cultural.",
      "points": 40,
      "type": "Proyecto",
      "raCode": "",
      "period": "P4",
      "project": 7,
      "gradingKind": "final",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-31",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-05-10",
      "code": "ACT-31",
      "number": 31,
      "title": "Clasificación de rubros y análisis de presupuestos modelo.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P4",
      "project": 8,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-32",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-05-17",
      "code": "ACT-32",
      "number": 32,
      "title": "Diseño de la hoja Excel/Calc y prueba de fórmulas.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P4",
      "project": 8,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-33",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-05-24",
      "code": "ACT-33",
      "number": 33,
      "title": "Cálculo de costos, revisión de fórmulas y preparación del pitch.",
      "points": null,
      "type": "Proceso",
      "raCode": "",
      "period": "P4",
      "project": 8,
      "gradingKind": "process",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    },
    {
      "id": "seed-ARTES-4H-ACT-34",
      "subjectKey": "ARTES-4H",
      "moduleCode": "",
      "materiaId": null,
      "date": "2027-05-31",
      "code": "ACT-34",
      "number": 34,
      "title": "Entrega/presentación del proyecto viable y cierre del portafolio anual.",
      "points": 40,
      "type": "Proyecto",
      "raCode": "",
      "period": "P4",
      "project": 8,
      "gradingKind": "final",
      "orientative": true,
      "source": "Listado_Actividades_Cortes_Identidad_Cultura_Emprendimiento_2026-2027.docx",
      "seeded": true
    }
  ]
};
